### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by danwalmsley** [AvaloniaUI/Avalonia.Native#5]
- [x] implement mouse input

- [x] implement mouse wheel

- [x] fix borderless windows

- [x] borderless window dragging

- [x] keyboard input (in progress)

- [x] clipboard

- [x] mouse cursor change

- [x] window activation / management

- [x] window position changed event

- [x] popups

- [x] top most

- [x] screens api

- [x] drag and drop

- [x] system dialogs

- [x] deferred rendering

- [x] icon loading

- [x] setminmax

- [x] rename stubs.cs

- [x] check for any remaining stubs

- [x] Test with existing apps like AvalonStudio and Wasabi Wallet

- [x] gpu rendering

- [x] azure Mac ci script

- [x] cake script to build, package and publish nuget packages.

- [x] ShowDialog on windows
